name: Laika Queue Test Suite

on:
  push:
    branches:
      - beta
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ########################################################
  # VALIDATE & LINT
  ########################################################
  test:
    name: Validate & Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      # Validate composer.json
      - name: Validate composer.json
        run: composer validate --no-check-publish

      # Lint PHP Syntax
      - name: Lint PHP syntax
        run: |
          find src helpers -name '*.php' -print0 | xargs -0 -n1 php -l
          php -l bin/worker
